// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIkz3WT9pxQJnuaujTXM6Q03pQZVx1Zwk',
    appId: '1:194701743878:web:63d507f64ae88daa86f087',
    messagingSenderId: '194701743878',
    projectId: 'object-detection-e95b0',
    authDomain: 'object-detection-e95b0.firebaseapp.com',
    storageBucket: 'object-detection-e95b0.appspot.com',
    measurementId: 'G-F8MFRTMRZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2WE1UXVxb4Empr_k7fG6Az_zO6kZLFqg',
    appId: '1:194701743878:android:c4368e44d70ea4fc86f087',
    messagingSenderId: '194701743878',
    projectId: 'object-detection-e95b0',
    storageBucket: 'object-detection-e95b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Gzt7gkCId1hX9_6ueQJcx7OXfDDhdb0',
    appId: '1:194701743878:ios:708240360348ab7586f087',
    messagingSenderId: '194701743878',
    projectId: 'object-detection-e95b0',
    storageBucket: 'object-detection-e95b0.appspot.com',
    iosClientId: '194701743878-j7ou12csv0spnqicvj4ic6pli9kr3lav.apps.googleusercontent.com',
    iosBundleId: 'com.example.objectDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Gzt7gkCId1hX9_6ueQJcx7OXfDDhdb0',
    appId: '1:194701743878:ios:708240360348ab7586f087',
    messagingSenderId: '194701743878',
    projectId: 'object-detection-e95b0',
    storageBucket: 'object-detection-e95b0.appspot.com',
    iosClientId: '194701743878-j7ou12csv0spnqicvj4ic6pli9kr3lav.apps.googleusercontent.com',
    iosBundleId: 'com.example.objectDetection',
  );
}
